[project]
name = "pluralmind"
version = "2.0.1"
description = "Let folks know who's speaking. Pluralmind allows plural folks to share which of their members is sending a message on Twitch."
readme = "README.md"
license = "MIT"
authors = [
    { name = "leahinmoonlight" },
]
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.25.1",
    "typing-extensions>=4.4.0",
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Communications :: Chat",
    "Typing :: Typed",
]

[project.urls]
Homepage = "https://pluralmind.chat/"
Documentation = "https://docs.pluralmind.chat"
Repository = "https://github.com/leahinmoonlight/pluralmind-py.git"
Issues = "https://github.com/leahinmoonlight/pluralmind-py/issues"
Changelog = "https://github.com/leahinmoonlight/pluralmind-py/releases"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pyright==1.1.411",
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
    "respx>=0.23.1",
    "ruff>=0.16.1",
]

[tool.pyright]
include = ["src", "tests"]
pythonVersion = "3.12"
typeCheckingMode = "strict"

[[tool.pyright.executionEnvironments]]
root = "tests"
reportMissingParameterType = false
reportUnknownParameterType = false
reportUnknownMemberType = false
reportUnknownArgumentType = false
reportUnknownVariableType = false

[tool.ruff]
target-version = "py312"
line-length = 120

[tool.ruff.format]
quote-style = "single"
preview = true

[tool.ruff.lint]
# https://docs.astral.sh/ruff/rules/
select = [
    # flake8-bugbear
    "B",
    # pydocstyle
    "D",
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # flake8-logging-format
    "G",
    # isort
    "I",
    # flake8-logging
    "LOG",
    # Ruff-specific rules
    "RUF",
    # flake8-simplify
    "SIM",
    # flake8-type-checking
    "TC",
    # pyupgrade
    "UP",
    # Warning
    "W",
]
ignore = [
    # Ignore missing docstrings
    "D1",
    # prefer D211: No blank lines allowed before class docstring
    "D203",
    # Don't require summary line
    "D205",
    # prefer D213: Multi-line docstring summary should start at the second line
    "D212",
    # Loosen first line of docstring rules
    "D400",
    "D404",
    "D415",
    # Don't require imperative mood
    "D401",
]

[tool.ruff.lint.pycodestyle]
max-doc-length = 80

[tool.pytest]
asyncio_mode = "auto"
testpaths = [
    "tests",
]
